schema-version: v1
kind: plugin
metadata:
  name: stk-plugin-angular-aws-cognito
  display-name: stk-plugin-angular-aws-cognito
  description: Add AWS Cognito to an angular project
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  repository: git@github.com:fabiopereirazup/stk-plugin-angular-aws-cognito.git
